### ISSUE TITLE
Meetup October 3rd

### ISSUE THREAD

**Issue by hanneoberman** [r-lgbtq/organisation#1]
## Set up

- [x] Decide date and time, preferably at least two weeks in advance: October 3rd
- [x] Decide purpose of meetup and whether there'll be any activity, e.g. show and tell or a speaker: Show and tell
- [x] Create event on Zoom, using Forwards account: <https://zoom.us> (Ella)
    - Make sure that registration is required
- [x] Create image to share (Ella)
- [x] ~~Add to RainbowR website (once events page is created!)~~

## Promote

- [x] RainbowR on Mastodon: <https://tech.lgbt/@rainbowR> (Hanne)
- [x] Share Mastodon login credentials with Hanne (Ella)
- [x] RainbowR Slack: <https://rainbowr.slack.com> (Hanne)
- [x] Forwards Slack: <https://rforwards.slack.com> (Ella)
- [x] Boost or send our reminder the day before (Hanne)
- [x] Draft e-mail reminder (Hanne)
- [x] Mail RainbowR community members (Ella)

## Prepare for meetup

- [x] Create an etherpad with outline and for writing/sharing any notes during the meeting:   [https://developer.r-project.org/etherpad/p/2023-10-03-rainbowR](https://developer.r-project.org/etherpad/p/2023-10-03-rainbowR)
  - simply create with a new URL in format <https://developer.r-project.org/etherpad/p/YYYY-MM-DD-rainbowR> (just update date!) (Hanne: add line about confidentiality of these notes)
  - see e.g. <https://developer.r-project.org/etherpad/p/2022-11-01-rainbowR>
  
## After meetup

- [x] back up etherpad notes by copying into a new .md file in <https://github.com/r-lgbtq/meeting-notes> (this is a private repo) (Hanne)

**Comment by hanneoberman** [comment]
# Draft e-mail reminder

@EllaKaye Could you please review this draft?

## Subject: Join us for the online rainbowR community meet-up!

Dear rainbowR community member,

We would like to welcome you to join the upcoming rainbowR community meet-up. 

![2023-10-03-rainbowR-meetup](https://github.com/r-lgbtq/organisation/assets/38891540/35579823-6050-436f-8c51-367f274a3776)
rainbowR meet-up: Tuesday October 3rd, 4pm UTC

You might have seen our invitation already through Slack or Mastodon (we're located at tech.lgbt/@rainbowR in the fediverse), but we’re going to start using this email list to announce upcoming events too. Don't worry, we won't spam: we're planning on e-mailing you only if there is an event coming up (once every one to three months).

We are looking forward to seeing you next week! Please feel welcome to join if you'd like to:
- Connect with other community members
- Enjoy a very informal, friendly and supportive 'show and tell' - would be lovely if you're willing to share something R-related you've been working on or like (not obligatory).
- Discuss about contributing to rainbowR

Register on Zoom (required):‪ https://us02web.zoom.us/meeting/register/tZApdOqqrDwrGNZxRxVAL2OoK1_XQrjSGXDl

See you there!

**Comment by EllaKaye** [comment]
Sent, with a few small tweaks. Thanks so much for preparing this 😄

**Comment by hanneoberman** [comment]
The meet-up went well! I'm closing this issue now :)

**Comment by EllaKaye** [comment]
It did indeed go well. Thank you :)
