### ISSUE TITLE
Meetup April 2024

### ISSUE THREAD

**Issue by hanneoberman** [r-lgbtq/organisation#5]
## Set up

- [x] Decide date and time, preferably at least two weeks in advance
- [x] Decide purpose of meetup and whether there'll be any activity, e.g. show and tell or a speaker
- [x] Create event on Zoom, using Forwards account: <https://zoom.us>
    - Make sure that registration is required
- [x] Create image to share
- [x] Add to RainbowR website (once events page is created!)

## Promote

- [x] RainbowR on Mastodon: <https://tech.lgbt/@rainbowR>
- [x] RainbowR Slack: <https://rainbowr.slack.com>
- [ ] Forwards Slack: <https://rforwards.slack.com>
- [x] Email list
- [x] Boost or send our reminder the day before

## Prepare for meetup

- [x] Create an etherpad with outline and for writing/sharing any notes during the meeting
  - simply create with a new URL in format <https://developer.r-project.org/etherpad/p/YYYY-MM-DD-rainbowR> (just update date!)
  - see e.g. <https://developer.r-project.org/etherpad/p/2024-02-22-rainbowR>
  
## After meetup

- [x] back up etherpad notes by copying into a new .md file in <https://github.com/r-lgbtq/meeting-notes> (this is a private repo)

**Comment by hanneoberman** [comment]
Date: Wednesday, April 3rd

- 10 AM UTC
- 10 PM UTC @EllaKaye or was it 8 PM???

**Comment by hanneoberman** [comment]
This is what I want to post on our fedi page:

🧪 rainbowR experiment! Our next community meetup will take place TWICE on Wednesday, April 3rd. At what time would you like to join?

**Comment by EllaKaye** [comment]
Hi Hanne! Thanks for getting started on this. We decided to try 10am UTC and 8pm UTC. Can I suggest the following slight edits to the fedi post:

🌈🧪 rainbowR experiment! Next month we're holding TWO meet-ups, to better suit people in a range of time-zones. Save the date for one, or both!

Date: Wednesday April 3rd
Times: 10am UTC and 8pm UTC

Sign-up details to follow a couple of weeks before.

**Comment by hanneoberman** [comment]
``` r
library(lubridate)
#> Warning: package 'lubridate' was built under R version 4.3.3
#> 
#> Attaching package: 'lubridate'
#> The following objects are masked from 'package:base':
#> 
#>     date, intersect, setdiff, union
ymd_hms("2024-04-03 10:00:00") |> with_tz("America/New_York")
#> [1] "2024-04-03 06:00:00 EDT"
ymd_hms("2024-04-03 20:00:00") |> with_tz("America/New_York")
#> [1] "2024-04-03 16:00:00 EDT"
```

<sup>Created on 2024-03-11 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by hanneoberman** [comment]
Here's the Etherpad: https://developer.r-project.org/etherpad/p/2024-04-03-rainbowR @EllaKaye how should we do this for the second meeting? Together in the same doc or a new naming convention for the address?

**Comment by EllaKaye** [comment]
Thanks! I'd lean towards two ether pads with a different naming convention. I've just set up:
https://developer.r-project.org/etherpad/p/2024-04-03_10amUTC-rainbowR
https://developer.r-project.org/etherpad/p/2024-04-03_8pmUTC-rainbowR
